### PR TITLE
fix(preset): set fallback when opacityVariable is empty

### PR DESCRIPTION
**Pull request by Codpoe**
If opacityVariable does not exist, consider using opacityValue.

### CODE REVIEW

**Comment by lianghx-319** [comment]
Glad to see your PR! I will check the preview deploy this weekend.

**Comment by Codpoe** [comment]
> Glad to see your PR! I will check the preview deploy this weekend.

I have sent another PR to fix this 😄  #6

**Comment by lianghx-319** [comment]
@Codpoe Can you sync the `main` branch, and re-trigger the preview process in this PR?

**Comment by Codpoe** [comment]
> 5:29:10 PM:   Error message
5:29:10 PM:   Deploy did not succeed: Deploy directory 'apps/docs/.vitepress/dist' does not exist
5:29:10 PM: ​
5:29:11 PM: Creating deploy upload records
5:29:10 PM:   Resolved config
5:29:10 PM:   build:
5:29:10 PM:     command: pnpm install || ( npm install -g pnpm && pnpm install && pnpm docs:build)

@lianghx-319 Is there something wrong with the build script set up in netlify? It seems that `pnpm docs: build` is not executed?

**Comment by lianghx-319** [comment]
- [ ] This PR will be merged after release gitHub action setup!

@Codpoe If you want to apply new version immediately, you can cantact me below.

**Pull request merged**
